name: "Deploy Storybook"
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Deploy Storybook
        run: |
          npm ci
          npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
