name: "Release"
on:
  push:
    branches:
      - master
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Deploy Storybook
        run: |
          npm ci
          npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Semantic Release
#        id: semantic
#        uses: cycjimmy/semantic-release-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#
#      - name: Publish Github Pages
#        if: steps.semantic.outputs.new_release_published == 'true'
